const express = require('express')
const app = express()
require('./models/db')
const bodyParser = require('body-parser')
const port = 3000
const router = require('./routes')
const {env} =require('./config')
console.log(env)
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:true}))
app.use('/api',router)
app.get('/', (req, res) => res.send('Hello World!'))
app.listen(port, () => console.log(`Example app listening on port port!`))